### PR TITLE
Add propTypes to all relevant components

### LINKED ISSUE #75: Use propTypes?
Small issue, I just noticed that we're not currently using `propTypes` in our components. Might make it easier for newcomers to navigate and contribute to the project as it grows if we did. Thoughts?

### PR DESCRIPTION
**Pull request by radotreyes**
Pretty sure I got all the propTypes right, no warnings being thrown anywhere. Added some missing props to `ChapterRouter` tests as well; I think this change will help spot holes in our tests as the project grows and changes. Should resolve #75.

Let me know if I missed anything.

### CODE REVIEW

**Comment by nikrb** [comment]
@radotreyes great work on the prop-types!

I have some notes below, but it's really up to @austintackaberry to decide overall code style.

1. It looks like you have fixed the ChapterRouter.js test, which is great, but really shouldn't be in a PR for prop-types :)
2. Generally put prop-types at the top, it's a good clue to anyone coming to the file afresh.
3. prop-types can be declared inside the class as a static:
```
class blahblah {
  static propTypes = {
    book: PropTypes.object.isRequired,
  };
  // ... rest of component
}
```

**Comment by radotreyes** [comment]
@nikrb my mistake, the ChapterRouter test was failing and it was a quick fix that didn't affect much else, so I figured it was free game fix it. But yes I'll try to touch as few files as possible. Thanks for bearing with me, still getting the hang of this...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nikrb** [comment]
haha yes, it's so tempting isn't it. Quick stash can help if you notice something like that - otherwise there's the chance it might be forgotten.
No worries dude, I'm learning all the time aswell :)

**Comment by austintackaberry** [comment]
I have not done anything with propTypes, so feel free to approve and merge when you're good @nikrb :slightly_smiling_face:

**Comment by radotreyes** [comment]
@nikrb for sure. If you'd like I'll just quickly move them for now to close this PR, and I can go back and refactor then with `.shape` in the near future?

**Comment by radotreyes** [comment]
Just tried to move everything, and I'm getting this when running tests:

image

It looks like we need to configure Babel in order for Jest (among other things?) to handle `statics`. I think [this one](https://babeljs.io/docs/en/babel-plugin-transform-class-properties/) is the one we're looking for. 

Should I make this change through my fork and just push the new `package.json`, or should I let one of the collaborators handle it?

**Comment by radotreyes** [comment]
Pushed the changes. Think we're good to go.

**Comment by nikrb** [comment]
I haven't seen that before. I usually use create-react-app to bootstrap projects so don't have much experience of babel presets.

**Pull request merged**
