### PR TITLE
Added questions to Up and Going Chapter 02

### PR DESCRIPTION
**Pull request by hakabuk**
Added questions to chapter 02 of Up and Going as described [here](https://github.com/austintackaberry/ydkjs-exercises/issues/1).

Please review.

### CODE REVIEW

**Comment by hakabuk** [comment]
I'm happy to try and fix this issue, but don't know how. Any guidance would be greatly appreciated.

**Comment by nikrb** [comment]
@hakabuk assume you're referring to the CI build failure?
beats me, `npm run build` locally works fine for me.

**Comment by hakabuk** [comment]
@nikrb Yes (should have been more specific). I'd love to fix this - if you have any suggestions on steps I should take - please let me know. Happy to try it!

**Comment by nikrb** [comment]
I'm not familiar with Travis. The only thing I can think of is hitting the rerun build button on the travis page, maybe there was a connection issue when the build ran - it does say it failed because the build stalled and a report is missing.

**Comment by hakabuk** [comment]
Thanks! According to [SO](https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit) since I don't have write access to the repo, I won't be able to initiate another build unless I close the PR and open it again.
I'm going to try it now.

**Comment by austintackaberry** [comment]
Not sure what the issue was, but when I re-ran the build, it worked.

**Comment by austintackaberry** [comment]
Merged. Thanks!

**Pull request merged**
