### PR TITLE
render 404 message for nested routes

### PR DESCRIPTION
**Pull request by jrobind**
Attempted fix for #47

I have wrapped nested routes in Switch components. Not sure if this is the best approach or not!

### CODE REVIEW

**Comment by austintackaberry** [comment]
This looks good to me. There appears to be merge conflicts. I will take a look at them either today or tomorrow.

**Comment by jrobind** [comment]
I've had another look, and there seems to be an issue with the routes when wrapped in the Switch component inside `ChapterRouter.js`.  Whenever the 'next' button is pressed it produces this error in the console:

screenshot 2018-06-01 15 11 16

I think the error may have something to do with the material-ui package. Also, `material-ui": "^0.20.0` is now deprecated . I'll be honest I've never used it before, so I'm not 100%! 

Removing the Switch component from `ChapterRouter.js` resolves the above console error, but this means there will not be a 404 handler for question routes.

**Comment by nikrb** [comment]
@austintackaberry @jrobind should we close this and create a new pr for new fix?
Forgive my nit-picking James but there is kinda a loose standard for branch names, e.g. fix/nested-404 might be a better name :) There are also standards for commit messages https://chris.beams.io/posts/git-commit/ . I come from freecodecamp who suggest [commitizen](https://github.com/commitizen/cz-cli) style which start with the type, e.g. fix, feat, docs etc. Hope this helps (and I'm not poking my nose in where it isn't wanted :)

**Comment by jrobind** [comment]
Fair enough. I have only just started contributing to open source so I will take your points on board.

**Pull request merged**
