### PR TITLE
JavaScript does have classes, according to multiple ECMAScript editors.

### PR DESCRIPTION
**Pull request by Jeff-Mott-OR**
Related to issue #148.

### CODE REVIEW

**Comment by radotreyes** [comment]
Can you elaborate on why these specific deletions are necessary?

**Comment by Jeff-Mott-OR** [comment]
@radotreyes
> question: It is better to think about object oriented programming in JavaScript as Object Links than Classes ... JavaScript simply does not have classes.

Both the premise and the "more info" of this question are wrong. Object links and classes are not mutually exclusive. Both Python's and Ruby's inheritance, for example, is implemented with object links. For example, JavaScript and Python side-by-side: https://i.imgur.com/p9Kw815.png. And the claim that JavaScript does not have classes is also flat wrong, and has been refuted by ECMAScript editors (links in #148).

> question: Which statement below best describes why OLOO is a better mental model than OOD in JavaScript ... There are no real classes in JavaScript, so true OOD is not possible

Again, ditto. OLOO and OOD are _not_ separate mental models. Python's and Ruby's class inheritance, for example, is objects linked to other objects. And JavaScript's classes are real, according to the ECMAScript editors themselves.

> question: What is the main fundamental concept of Delegation-Oriented Design in comparison to the traditional Object-Oriented Design? ... Fundamentally, the prototype chain does not have a concept of "copying"

Kyle's idea of "traditional" OOD is wrong. Neither Python's nor Ruby's nor Smalltalk's class inheritance behaves in the way that Kyle considers traditional. For context, Python pre-dates Java, and Smalltalk pre-dates C++.

----

The unfortunate fact is YDKJS is not gospel. Kyle made mistakes. Probably more than we'd like to admit. Kyle says he plans to "significantly revise the text in the second edition," but in the meantime, I don't think we should perpetuate the mistakes of his first edition.

**Comment by Jeff-Mott-OR** [comment]
I don't think those questions can be fixed by a simple re-wording. They're based on and assume a premise that is itself wrong.

**Comment by radotreyes** [comment]
Maybe "re-word" is the wrong term. What I had in mind was to re-shape the questions so that the range of topics they cover is still present in the chapter, rather than to remove that content altogether. Basically, OOD/OLOO should still have coverage, but they should not be presented as they are now.

I trust your judgment, so if you're up to making those kinds of changes, I'll leave it to you in this PR. Otherwise I think it would be best to open an issue so we can discuss what these questions could possibly be replaced with.

**Comment by Jeff-Mott-OR** [comment]
Sorry I don't have different questions to replace these with.

**Comment by radotreyes** [comment]
I'll be closing this PR then, but we'll definitely evaluate the questions you brought up and will replace them in kind.

**Comment by Jeff-Mott-OR** [comment]
Personally I think that's the wrong approach. That's a quantity over quality kind of decision. You're choosing to keep bad information because you want to maintain a quota of questions.

**Comment by radotreyes** [comment]
I appreciate you taking the time to open this PR, as it does raise a real issue. It seems like we agree that the information in the questions you raised isn't up to par.

However, simply removing the questions isn't an ideal solution either. This project is about giving people learning JavaScript a comprehensive resource to test their knowledge against a text that's held in fairly high regard amongst this community. 

You're referring to past targets of 5-10 questions per chapter; that was one way to ensure that we cover most of the subject material provided by YDKJS. Whether or not that was a good goal, that's not why I want to replace the questions.

Imagine that same math textbook has chapters on addition, subtraction, multiplication, and division. The multiplication section has errors, so in the next publication it is removed. Is that a good math textbook?

OLOO/OOD should still have coverage. Merging a PR which completely removes that coverage isn't in the best interest of this project. I'd advise you to open an issue if this is a large concern for you, I'm open to discussing there.

**Comment by Jeff-Mott-OR** [comment]
> Imagine a math textbook has chapters on addition, subtraction, multiplication, and division. The multiplication section has errors, so in the next publication it is removed. Is that a good math textbook?

It's probably a better textbook, yes. I'm not talking about one or two minor mistakes. I'm talking about whole chapters based on a faulty premise. Imagine your math textbook with a whole chapter around the premise that 1x1=2. Is it better to keep that chapter in so that multiplication has "coverage"?

**Comment by radotreyes** [comment]
If you think that the mistakes in YDKJS, and I agree that they are mistakes, are so fundamentally flawed that they do more harm than good, then I don't share your opinion to that extent. Thanks for the PR. We'll work on this issue separately.

**Pull request closed without merging**
