### PR TITLE
Fixed explanation flowing out of border

### PR DESCRIPTION
**Pull request by hakabuk**
As discussed on https://github.com/austintackaberry/ydkjs-exercises/issues/71

### CODE REVIEW

**Comment by hakabuk** [comment]
Sure thing, @austintackaberry !

**Comment by austintackaberry** [comment]
Definitely a good thing to change height to min-height, nice catch!

I misspoke...I said setting min-width on my previous comment, but I meant setting a max-width. That way it takes up the full width on mobile but not on desktop. What do you think about that?

**Comment by radotreyes** [comment]
@hakabuk @austintackaberry are you guys trying to address this?
image

I think contributing to the problem is that App.css doesn't have any properties such that the App component dynamically resizes in the browser. There may also be issues with how I chose to implement the sidebar as well (Didn't use any flexbox or grid). I could be wrong though, let me know what solution you find 🙂

**Comment by austintackaberry** [comment]
I think setting a max width to like 800px or something should fix that. The only other thing to fix is that on mobile, we probably don't want the border around the question. Adding a media query should fix that, but that doesn't have to be in this PR.

**Comment by hakabuk** [comment]
I'll update these changes and push it again. Great idea! 
Btw I'm more than happy to suggest mockups for question/chapter page design (suggest a colour palette and a different font, perhaps), if you'd like :) I understand if it's too early for that, though

**Comment by hakabuk** [comment]
I've made the changes. I also tried replacing the border with a bright overlay background, and I think it makes more sense this way. The reason is in mobile the border looked like two horizontal lines, and I feel an overlay brings the attention to the question. I'm more than happy to change it back if anyone apposes.  
screen shot 2018-07-01 at 11 36 26

**Comment by austintackaberry** [comment]
If you have any ideas for design/colors, feel free to open up an issue on github! I think what you came up for mobile looks good :+1:

**Comment by hakabuk** [comment]
Thanks for the feedback, @austintackaberry ! I'd like to give a few hours to try and think of a colour scheme. I love the blue, but I think it can be a mixture of colours. I'll give it a try. 

I'm more than happy to use media queries, but I think for now it looks OK on both mobile and desktop, so I rather concentrate on creating more questions and learning more from you don't know JS :) ! 

I'm happy with the current state, and I fixed the conflict with the padding. Feel free to merge :)

**Pull request merged**
