### PR TITLE
added randomization of answers and changed variable name to shouldBeR…

### PR DESCRIPTION
**Pull request by kevinsmithwebdev**
So I added randomization. I had an issue doing it in the Question component - every time the component rerendered, it would rerandomize, even if it was just to change the highlighting of the correct answer. I settled for doing the randomization at load time, in the file /home/kevin/dev/ydk/src/data/index.js.

I also converted the properties *orderedById* to *shouldBeRandomized* and inverted the logic in the data files.

### CODE REVIEW

**Comment by austintackaberry** [comment]
Looks like the build is failing due to a failed test. I think this test expects a specific order for the answers. Perhaps we should change it to have `shouldBeRandomized` to false in order to preserve the order for the test.

**Comment by kevinsmithwebdev** [comment]
That is an option. Instead I moved the failing test to another question that is not randomized - in this case *Types and Grammar* chapter 2, question 1. It's true/false so it doesn't need to be randomized. The test passes on my machine now. (Sorry, I didn't think to check that before.)

**Comment by austintackaberry** [comment]
The only problem with doing that is that we could change Types and Grammar chapter 2, question 1 in the future to a question that should be randomized which would break our test.

**Comment by kevinsmithwebdev** [comment]
@austintackaberry But couldn't that be true of any question?

@nikrb Yes, I considered that possibility, but don't know enough about jest to code that. I tried this for a bit but couldn't get it to work. I can look into it more.

Another possibility I considered is to break up the loading of the Qs into two files. The first one *rawData.js* just loads them and then *data.js* does the randomization. Then the test could load from *rawData.js*. I tried this but for some reason the test suite was still getting randomized answers.

It seems like nikrb's suggestion would be the most robust - the other methods could always break depending on what changes people made to the questions/answers.

**Comment by kevinsmithwebdev** [comment]
OK, I came up with another solution. I messed around with jest until I found a test that works. The test was:
```
  expect(
    comp
      .find('ReactMarkdown')
      .at(1)
      .props().source
  ).toBe(
    'A set of special instructions to tell the computer what tasks to perform.'
  );
```

and now I have:

```
  expect(
    comp
      .find('ReactMarkdown')
      .find('[source="A set of special instructions to tell the computer what tasks to perform."]')
      .exists()
  ).toEqual(true);
```
This (afaik) will do the same thing as before, but instead of looking at a specific answer slot, it will just check if that answer exists in any of the the slots. This way it won't care if the answer is randomized.

**Comment by nikrb** [comment]
looks good to me, but I think @austintackaberry  issue is, if someone changes the text then the test breaks. Hopefully he has a suggestion.

**Comment by kevinsmithwebdev** [comment]
My perception was that he was more concerned about the randomization flag being changed. But the idea of hard coding the exact answer string into the test seemed a bit odd to me. We could load the answer string at the same time we load the question string. Of course, that assumes that we know how many answers there are - we can always assume there are two, but that would never check later answers. Of course, we could randomly select an answer or even check them all - load them in an array and map through them. Just some thoughts.

**Comment by austintackaberry** [comment]
This is a good use case for either fake data or manipulated real data. For the test's sake, we could force the question to have `shouldBeRandomized: true` and then check to make sure the 3rd answer is rendered as the 3rd answer.

Honestly though, thinking about it now, we will be changing our tests so much as a result of https://github.com/austintackaberry/ydkjs-exercises/issues/119 that it doesn't matter that much to me for this PR. We can just fix it as a result of fixing that issue.

**Comment by austintackaberry** [comment]
@kevinsmithwebdev Thanks for your contribution and being open to suggestions!

**Pull request merged**
